### ISSUE TITLE
Immunity not preventing additional events from happening

### ISSUE THREAD

**Issue by zterner-mitre** [RobinDenz1/simDAG#3]
Hi Robin,
[simDAG - waning vax - Git - immunity bug.txt](https://github.com/RobinDenz1/simDAG/files/14426131/simDAG.-.waning.vax.-.Git.-.immunity.bug.txt)

In the attached R script, I have set the immunity for my vaccination node to be Inf. But there are many cases where people get vaccinated more than once.

I have found a workaround for this issue, but I wanted to bring your attention to the issue in the code anyway.

For reference, here is the specification of the model. (It's also in the code of course but thought it might help to show it here.)
<img width="613" alt="image" src="https://github.com/RobinDenz1/simDAG/assets/117375468/189494ad-63ad-4ea2-89c2-71c249a4fdc3">

That image doesn't show the prob functions for the other nodes, but those are in the code, and I don't see why those should be contributing to people getting vaccinated more than once.

Again, it's easy enough to fix this -- an `fifelse` to prevent people from getting vaccinated based on the time_since_last works fine -- but wanted you to know that immunity may not be functioning as intended.

**Comment by RobinDenz1** [comment]
Thank you for your report. This is indeed a bug in the `node_time_to_event()` function. I will push an update resolving this bug to github in a minute.
