### ISSUE TITLE
Example of specifying betas for parent three-level categorical variable

### ISSUE THREAD

**Issue by cegepi** [RobinDenz1/simDAG#5]
Awesome package, Robin - using it to create some simulated datasets for my class! Would you be able to provide an example of how to specify the betas for the scenario where a binomial child node (e.g., drug) is dependent on a parent node that is categorical/multinomial (with 3 levels). In my mind I want to supply two coefficients for the three-level predictor (indicator variable coding with a reference level), but I get the error:

> 'betas' must have the same length as 'parents' when using type='binomial'.

Code for my DAG:
`dag <- empty_dag() +
  node("comorbidity", type="rcategorical", labels= c("low","medium","high"), probs = c(0.30, 0.40, 0.30)) +
  node("grade", type="rbernoulli", p=0.5) +
  node("stage", type="binomial", parents=c("grade"), betas=c( 0.4637), intercept=-.405) +
  node("drug", type = "binomial", parents = c("stage", "comorbidity"), betas=c(-0.162,-0.083,-0.248), intercept= -0.50)`

In this example, comorbidity is a three-level root node with potential values low, medium, and high. Drug depends on stage (binomial) and comorbidity where the coefficients for medium and high levels of comorbidity are -0.083 and -0.248, compared to reference level of low. Is there a way to do this in simDAG that I am not seeing?

Thanks for entertaining my question!

**Comment by RobinDenz1** [comment]
Thanks for the kind words.

Using categorical variables in dummy coded format is currently not directly supported by the `node_binomial()` function, mainly because I didn't have a good idea yet how to make the specification of such nodes clear. However, since you can use any kind of function to generate a new node you can do something like this to get what you are looking for:

```R
## binomial regression, but allowing categorical variables as independent
## variables directly
node_binomial_custom <- function(data, parents, ...) {
  
  form <- stats::as.formula(paste0("~ ", paste0(parents, collapse=" + ")))
  
  mod_mat <- model.matrix(form, data)
  mod_mat <- mod_mat[, 2:ncol(mod_mat)]
  
  out <- node_binomial(data=as.data.table(mod_mat), parents=colnames(mod_mat),
                       ...)
  
  return(out)
}

# specify your DAG (only thing i changed is the "coerce2factor" argument of the comorbidity node and
# the type of the "drug" node
dag <- empty_dag() + 
  node("comorbidity", type="rcategorical", labels= c("low","medium","high"),
       probs=c(0.30, 0.40, 0.30), coerce2factor=TRUE) + 
  node("grade", type="rbernoulli", p=0.5) + 
  node("stage", type="binomial", parents=c("grade"), betas=c( 0.4637), intercept=-.405) + 
  node("drug", type="binomial_custom", parents=c("stage", "comorbidity"),
       betas=c(-0.162,-0.083,-0.248), intercept=-0.50)

dat <- sim_from_dag(dag, n_sim=100000)

# check if its working
mod <- glm(drug ~ stage + comorbidity, data=dat, family="binomial")
summary(mod)  
```
 This may seem a littly hacky, but it does the trick. I am planning on adding a better option to supply formulas similar to the `simcausal` package, but i haven't gotten around to it yet.

**Comment by RobinDenz1** [comment]
I have added a small change that allows you to use the `formula` argument to easily get what you were looking for. In your example you can run:

```R
dag <- empty_dag() + 
  node("comorbidity", type="rcategorical", labels= c("low","medium","high"),
       probs=c(0.30, 0.40, 0.30), coerce2factor=TRUE) + 
  node("grade", type="rbernoulli", p=0.5) + 
  node("stage", type="binomial", parents=c("grade"), betas=c( 0.4637), intercept=-.405) + 
  node("drug", type="binomial", formula= ~ stage + comorbidity,
       betas=c(-0.162,-0.083,-0.248), intercept=-0.50)

dat <- sim_from_dag(dag, n_sim=100000)

# check if its working
mod <- glm(drug ~ stage + comorbidity, data=dat, family="binomial")
summary(mod)  
```
This will work as you originally thought it would. Only thing you need to do is to use the `formula` argument instead of the `parents` argument.
