### ISSUE TITLE
Recovering the causal coefficients

### ISSUE THREAD

**Issue by abduazizR** [RobinDenz1/simDAG#6]
Hi

First, I would like to thank you for the awesome package. I am interested in learning about running simulations and plan to use the package.

I am currently reading through the vignette.

I noticed that I cannot recover the same coefficients in this example.

Below is a reproducible example

``` r
library(simDAG)


set.seed(545637)

dag <- empty_dag() +
  node("age", type = "rnorm", mean = 50, sd = 4) +
  node("sex", type = "rbernoulli", p = 0.5) +
  node("bmi",
    type = "gaussian", parents = c("age", "sex"), betas = c(1.1, 0.4),
    intercept = 12, error = 2
  ) +
  node("death",
    type = "binomial", parents = c("age", "bmi"), betas = c(0.1, 0.3),
    intercept = -15
  )

sim_dat <- sim_from_dag(dag, n_sim = 10000)

mod_death <- glm(death ~ age + bmi, data = sim_dat, family = "binomial")
summary(mod_death)
#> 
#> Call:
#> glm(formula = death ~ age + bmi, family = "binomial", data = sim_dat)
#> 
#> Coefficients:
#>              Estimate Std. Error z value Pr(>|z|)
#> (Intercept) -12.33804   12.70557  -0.971    0.332
#> age           0.01947    0.60772   0.032    0.974
#> bmi           0.32633    0.50522   0.646    0.518
#> 
#> (Dispersion parameter for binomial family taken to be 1)
#> 
#>     Null deviance: 20.421  on 9999  degrees of freedom
#> Residual deviance: 17.793  on 9997  degrees of freedom
#> AIC: 23.793
#> 
#> Number of Fisher Scoring iterations: 13
```

``` r


# try to exponentiate (not consistent)
exp(0.01947)
#> [1] 1.019661
```

``` r
exp(0.32633)
#> [1] 1.385873
```

<sup>Created on 2024-09-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Is there something I am doing incorrectly?

**Comment by RobinDenz1** [comment]
Thanks for your interest in this package.

First, the `betas` argument actually specifies the beta-coefficients of the model, not the odds-ratios (exponentiated coefficients). So we would expect the coefficients of the model as shown in the `summary()` output to approximately match the input, not the exponentiated versions of them.

Secondly, it is important to note that we are sampling from the true data generation process here. We will therefore never recover the exact coefficients that you put in, but you will get more and more close the larger the sample size gets. In your example, if you add two zeros to the `n_sim` argument, you will see that the coefficients are very close to the ones you specified.

The example I used isn't optimal in the sense that the coefficients are rather small while the intercepts and random errors are rather large, which means that a larger sample size is neccessary to get really close results. But if you repeated this simulation 1000s of times (even with small `n_sim`), you would get the correct coefficients on average over all simulation runs. Hope this helps!

**Comment by abduazizR** [comment]
Thanks for the prompt response. I tried to simulate 10000 individuals for 10000 times. See the code below.



```

dag <- empty_dag() +
  node("age", type = "rnorm", mean = 50, sd = 4) +
  node("sex", type = "rbernoulli", p = 0.5) +
  node("bmi",
    type = "gaussian", parents = c("age", "sex"), betas = c(1.2, 0.7),
    intercept = 12, error = 2
  ) +
  node("death",
    type = "binomial", parents = c("age", "bmi"), betas = c(0.7, 0.3),
    intercept = -15
  )

sim_dat <- sim_from_dag(dag, n_sim = 10000)

estimates_tbl <- tibble(sim_id = rep(NA, 10000), estimate = rep(NA, 10000))

# warning (this would take some time)
for (i in 1:10000) {
  mod <- sim_from_dag(dag, n_sim = 10000) |>
    glm(death ~ age + bmi, data = _, family = "binomial")

  estimates_tbl$sim_id[i] <- i
  estimates_tbl$estimate[i] <- mod$coefficients[["age"]]
}

library(ggplot2)

ture_coefficient = 0.7

estimates_tbl |> 
    ggplot(aes(x = estimate)) + geom_histogram() +
    geom_vline(xintercept = ture_coefficient)
```


This is how the distribution of the age estimates looks like

<img width="446" alt="image" src="https://github.com/user-attachments/assets/d76ea874-a8ca-4f41-a1b3-f50469ce0428">

It's centered around zero, and it's very far from the true coefficient I specified, i.e. 0.7

It's worth noting that I don't face this issue with `gaussian` nodes.

``` r
library(simDAG)
library(tidyverse)
dag <- empty_dag() +
  node("age", type = "rnorm", mean = 50, sd = 4) +
  node("sex", type = "rbernoulli", p = 0.5) +
  node("bmi",
    type = "gaussian", parents = c("age", "sex"), betas = c(1.2, 0.7),
    intercept = 12, error = 2
  ) +
  node("death",
    type = "binomial", parents = c("age", "bmi"), betas = c(0.7, 0.3),
    intercept = -15
  )

sim_dat <- sim_from_dag(dag, n_sim = 10000)

estimates_tbl <- tibble(sim_id = rep(NA, 10000), estimate = rep(NA, 10000))


# warning (this would take some time)
for (i in 1:1000) {
  mod <- sim_from_dag(dag, n_sim = 1000) |>
    glm(bmi ~ age + sex, data = _, family = "gaussian")

  estimates_tbl$sim_id[i] <- i
  estimates_tbl$estimate[i] <- mod$coefficients[["age"]]
}


ture_coefficient <- 1.2

estimates_tbl |>
  ggplot(aes(x = estimate)) +
  geom_histogram() +
  geom_vline(xintercept = ture_coefficient)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 9000 rows containing non-finite outside the scale range
#> (`stat_bin()`).
```

![](https://i.imgur.com/XOYcjNT.png)

<sup>Created on 2024-09-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by RobinDenz1** [comment]
The reason for this behavior is that the data generation process you specified leads to the `death` node being `TRUE` in almost all cases. You can check this by generating just one dataset and running `table(sim_dat$death)` afterwards. In cases like this the model will be unable to fit properly, because the outcome is essentially constant.  Try setting the intercept of the `death` node to something like -55 and you will see that it works perfectly fine.

**Comment by abduazizR** [comment]
Interesting. I can confirm that it's now working fine. I am wondering why setting -55 is different from -15. When you take the inverse logit of the two numbers, both are essentially zero.

**Comment by RobinDenz1** [comment]
Great! That might be true, but what matters is not the inverse logit of the intercept, but the logit of the linear combination of the intercept, variable values and coefficients. It seems that setting it to -55 ensures that the resulting probabilities are not too extreme in either direction.
